- name: Test if the provider is supported.
  meta: end_play
  when: ovmt_parameters.provider|lower != 'vmware'

- name: Gather facts on the system.
  setup:

- name: Install Dependencies.
  package:
    name: "{{item}}"
    state: present
  with_items: "{{ovmt_dependencies[ovmt_parameters.target]}}"

- name: Start Open VM Tools
  service:
    name: vmtoolsd
    state: started
    enabled: yes
