- name: Validate | Test if the target is graphical.
  set_fact:
    vbox_nox11: '--nox11'
  when: vbox_parameters.target != 'desktop'

- name: Set | Include Dependencies Variables
  include_vars: "{{role_path}}/defaults/vbox_{{ansible_os_family|lower}}_dependencies.yaml"

- name: Update | Optionally Update Kernel
  include: "{{role_path}}/tasks/update_{{ansible_os_family|lower}}_kernel.yaml"

- name: Install | Install Dependencies.
  package:
    name: "{{item}}"
    state: present
  with_items: "{{vbox_dependencies}}"

- name: Verify VBoxGuestAdditions.iso exists.
  stat:
    path: "/tmp/{{vbox_iso}}"
  register: vbox_stat

- name: Get | Download VirtualBox guest additions ISO to the system.
  get_url:
    url: "{{vbox_url}}"
    dest: "/tmp"
  when: not vbox_stat.stat.exists

- name: Mount | Mount VirtualBox guest additions ISO.
  mount:
    path: /tmp/vbox
    src: "/tmp/{{vbox_iso}}"
    opts: loop
    fstype: iso9660
    state: mounted

- name: Install | Install VirtualBox guest additions.
  command: "./VBoxLinuxAdditions.run {{vbox_nox11}}"
  args:
    chdir: /tmp/vbox

- name: Unmount | Unmount VirtualBox guest additions ISO.
  mount:
    path: /tmp/vbox
    state: absent

- name: Delete | Delete VirtualBox ISO from the system.
  file:
    path: "/tmp/{{vbox_iso}}"
    state: absent

- name: Clean VirtualBox guest additions Install Dependencies
  package:
    name: "{{item}}"
    state: present
  with_items: "{{vbox_dependencies}}"

# Note(Dan): This fixes issues with the guest additions video driver not
#            working until after two of reboots.
- name: Reboot the system.
  include_role:
    name: reboot_system
  vars:
    reboot_system:
      user: root
      host: localhost
      port: "{{oobm_port}}"
      count: 2
  when:
    - vbox_parameters.target == 'desktop'
    - oobm_port is defined
