# Validate Role
# -------------


# Execute Role
# ------------
- name: Install Virtualbox Guest Additions
  include: "{{role_path}}/tasks/install_virtualbox_guest_additions.yaml"
  when:
    - vbox_parameters.provider|lower == "virtualbox"
