# Validate Role
# -------------


# Execute Role
# ------------
- name: Install Gnome Preferences
  include: "{{role_path}}/tasks/install_gnome_preferences.yaml"
  when:
    - gp_parameters.target == "desktop"
