# Validate Role
# -------------
- name: Gather Facts
  setup:
  when: ansible_os_family is not defined


# Execute Role
# ------------
- name: Install EPEL
  include: "{{role_path}}/tasks/install_epel.yaml"
  when:
    - ansible_os_family == "RedHat"
